name: Build and Publish image for Devopsnoob.com
on: 
    schedule:
        # At 00:00 on day-of-month 1
        - cron: '0 0 1 * *'
        # At 00:00 on day-of-month 15
        - cron: '0 0 15 * *'
    workflow_dispatch:

      
    

jobs:
    Build_Image_and_Publish_to_Docker_hub:
      runs-on: ubuntu-latest

      steps:
        - name: checkout
          uses: actions/checkout@v4
          
       
        - name: Build Image
          run: |
            docker build -t rdeselle07/devopsnoob-com-mkdocs:latest .
      
            
        - name: Publish Image to Docker Hub
          run: |
            docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker push rdeselle07/devopsnoob-com-mkdocs:latest            