name: Build and Publish image for Devopsnoob.com
on: 
    [workflow_dispatch]
#   push:
#     branches: main
      
    

jobs:
    publish_image:
      runs-on: ubuntu-latest

      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Build Image
          run: |
            docker build --file ../../Dockerfile -t rdeselle07/devopsnoob-com-mkdocs:latest
      
        # - name: Login to Docker Hub
        #   uses: docker/login-action@v3
        #   with:
        #     username: ${{ vars.DOCKERHUB_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Publish Image to Docker Hub
          run: |
            docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker push -t rdeselle07/devopsnoob-com-mkdocs:latest
        
            